import { getAllTables, updateTableStatus, getAllProducts, auth, getUserProfile, onAuthStateChanged, signOut } from "./firebase.js"
const labels = { available: "Disponible", occupied: "Ocupada", reserved: "Reservada", cuenta_solicitada: "Lista para pago", en_limpieza: "En limpieza" }
const escape = (value) => String(value ?? "").replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character])
let tables = []; let authorized = false
const tableClass = (status) => status === "reserved" ? "reserved" : status === "occupied" ? "occupied" : status === "cuenta_solicitada" ? "payment" : "available"
function render() { const root = document.getElementById("waiterTables"); root.innerHTML = tables.length ? tables.map((table, index) => { const position = table.position || { x: 10 + (index % 4) * 23, y: 12 + Math.floor(index / 4) * 28 }; return `<button class="plan-table ${tableClass(table.status || "available")}" data-table="${table.id}" style="left:${position.x}%;top:${position.y}%"><strong>${escape(table.name)}</strong><small>${labels[table.status || "available"]}</small></button>` }).join("") : '<p class="empty-tables">No hay mesas configuradas.</p>' }
async function load() { const result = await getAllTables(); tables = result.tables || []; render() }
function closeModal(modal) { modal.remove() }
async function openProductMenu(table) { const result = await getAllProducts(); const products = result.products || []; const groups = products.reduce((all, product) => { (all[product.category || "Otros"] ||= []).push(product); return all }, {}); const modal = document.createElement("div"); modal.className = "modal"; modal.style.display = "flex"; modal.innerHTML = `<div class="modal-content waiter-menu-modal"><button class="close">&times;</button><h2>Agregar productos · ${escape(table.name)}</h2><div class="waiter-menu-list">${Object.entries(groups).map(([category, items]) => `<details open><summary>${escape(category)}</summary>${items.map((item) => `<article class="waiter-product"><img src="${escape(item.image || "https://via.placeholder.com/80")}" alt=""><div><strong>${escape(item.name)}</strong><p>${escape(item.description || "")}</p><span>$${Number(item.price || 0).toLocaleString("es-CO")}</span></div><input type="number" min="0" value="0" data-product="${item.id}"></article>`).join("")}</details>`).join("") || '<p>No hay productos disponibles.</p>'}</div><button class="btn btn-primary" data-add>Agregar al pedido</button></div>`; document.body.appendChild(modal); modal.querySelector(".close").onclick = () => closeModal(modal); modal.querySelector("[data-add]").onclick = () => { const selected = [...modal.querySelectorAll("[data-product]")].map((input) => ({ product: products.find((item) => item.id === input.dataset.product), quantity: Number(input.value) })).filter((item) => item.product && item.quantity > 0); if (!selected.length) return; const cart = JSON.parse(localStorage.getItem("cart") || "[]"); selected.forEach(({ product, quantity }) => { const existing = cart.find((item) => item.id === product.id); if (existing) existing.quantity += quantity; else cart.push({ ...product, quantity }) }); localStorage.setItem("cart", JSON.stringify(cart)); localStorage.setItem("activeWaiterTable", JSON.stringify({ id: table.id, name: table.name })); location.href = "cart.html" } }
function openTable(table) { const modal = document.createElement("div"); modal.className = "modal"; modal.style.display = "flex"; modal.innerHTML = `<div class="modal-content table-detail"><button class="close">&times;</button><h2>${escape(table.name)}</h2><p><strong>Estado:</strong> ${labels[table.status || "available"]}</p><p><strong>Capacidad:</strong> ${table.seats || 0} puestos</p><div class="form-buttons"><button class="btn btn-primary" data-products>Agregar productos</button><button class="btn btn-success" data-finish>Solicitar finalizar mesa</button></div></div>`; document.body.appendChild(modal); modal.querySelector(".close").onclick = () => closeModal(modal); modal.querySelector("[data-products]").onclick = () => { closeModal(modal); openProductMenu(table) }; modal.querySelector("[data-finish]").onclick = async () => { await updateTableStatus(table.id, "cuenta_solicitada", table.activeOrderId || null); closeModal(modal); load() } }
document.addEventListener("DOMContentLoaded", () => { onAuthStateChanged(auth, async (firebaseUser) => { if (!firebaseUser) return location.href = "inicioSesion.html"; const profile = await getUserProfile(firebaseUser.uid); if (!profile.success || !["admin", "mesero"].includes(profile.user.role)) { await signOut(auth); return location.href = "inicioSesion.html" } authorized = true; load() }); document.addEventListener("click", (event) => { const node = event.target.closest("[data-table]"); if (node && authorized) { const table = tables.find((item) => item.id === node.dataset.table); if (table) openTable(table) } }) })